services:
  postgres:
    image: postgres:latest
    ports:
        - "5432:5432"

#   Container will restart automatically if it stops
    restart: always
    environment:
#        Default username is postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
        - "8888:8080"

#  KeyCloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
        - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file



volumes:
  postgres-data:
  keycloak-data:
    driver: local